include(
    ":app",
    ":sample",
    ":navigation",
    ":common:cache",
    ":common:network",
    ":common:resources",
    ":common:views",
    ":features:home",
    ":features:onboarding",
    ":libs:usermanager"
)
