import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val com_squareup_retrofit2: String = "2.9.0"

    const val org_jetbrains_kotlin: String = "1.5.0"

    const val com_android_tools_build_gradle: String = "4.1.3"

    const val com_google_android_play_core: String = "1.10.0"

    const val logging_interceptor: String = "4.9.1"

    const val leakcanary_android: String = "2.7"

    const val swiperefreshlayout: String = "1.1.0"

    const val constraintlayout: String = "2.0.4"

    const val epoxy_processor: String = "4.5.0"

    const val recyclerview: String = "1.2.0"

    const val lint_gradle: String = "27.1.3"

    const val appcompat: String = "1.3.0-rc01"

    const val core_ktx: String = "1.6.0-alpha03"

    const val material: String = "1.3.0"

    const val rxpaper2: String = "1.5.0"

    const val lottie: String = "3.7.0"

    const val timber: String = "4.7.1"

    const val aapt2: String = "4.1.3-6503028"

    const val epoxy: String = "4.5.0"

    const val glide: String = "4.12.0"

    const val moshi: String = "1.12.0"

    const val junit: String = "4.13.2"

    const val mockk: String = "1.11.0"

    const val mavericks: String = "2.2.0"
}
